News CRUD를 구현한다.
DeliverBle/deliverble-backend-nestjs pull request #17
Opened 2022-09-13 11:42 UTC by horsehair

- news/create 구현
- news/all 구현 -> 전체 뉴스 조회
- news/update 구현 -> 특정 id의 뉴스 수정
- news/delete 구현 -> 특정 id의 뉴스 삭제

** 4가지 API 모두 전체 뉴스를 조회한 결과를 반환하도록 구현했습니다.

2022-09-13 13:46 UTC, sigridjineth requested changes
수고하셨습니다.

2022-09-13 13:46 UTC, sigridjineth commented on src/news/news.controller.ts
> +    ): Promise<News[] | void> {
일급 객체 만들어서 감싸주세요. void 없앱시다.
`NewsReturnDTOCollection` 이런 식으로요.

2022-09-13 13:46 UTC, sigridjineth commented on src/news/news.controller.ts
> +    @Post('update/:id')
REST API 규격 상 자원 / 행위 / 아이디를 순차적으로 표기합니다.
예를 들어, `news/update/1` 가 되겠네요.

2022-09-13 13:46 UTC, sigridjineth commented on src/news/news.repository.ts
> +        await this.delete(
여기서 `delete` 의 반환값은 뭐에요? 에러 핸들링을 하는 부분은 필요없나요?

2022-09-13 13:46 UTC, sigridjineth commented on src/news/news.service.ts
> +    async updateAndGetAllNews(id: number, updateNewsDto: UpdateNewsDto) : Promise<News[] | void> {
update와 getAllNews는 서로 다른 책임을 가진 엄연히 다른 피쳐인데 하나의 메소드에 모두 묶는 것은 옳지 않다고 생각해요.

2022-09-13 13:46 UTC, sigridjineth commented on src/news/news.service.ts
> +    async updateAndGetAllNews(id: number, updateNewsDto: UpdateNewsDto) : Promise<News[] | void> {
Repository의 메소드 하나는 하나의 역할만 수행해주세요. 만약 Service 객체가 뉴스 전체를 가져오는 행위를 해야 한다면 삭제 기능을 핸들링 한 후에 뉴스 전체를 가져오는 행위를 하는 메소드를 추가로 호출하게 해주세요.

2022-09-13 13:46 UTC, sigridjineth commented on src/news/news.service.ts
> +        return await this.getAllNews();
여기도 마찬가지구요.

2022-09-13 13:46 UTC, sigridjineth commented on src/user/user.service.ts
> +    const userInfoForView = new UserInfoForView(
DTO라고 명명해주시는게 훨씬 직관적일 것 같아요.

2022-09-21 10:25 UTC, horsehair commented on src/news/news.controller.ts
> +    ): Promise<News[] | void> {
적용해보았습니다! 아래에 푸쉬하였습니다.

2022-09-21 10:26 UTC, horsehair commented on src/news/news.controller.ts
> +    @Post('update/:id')
현재 `news/update/1` 과 같은 순서로 적용이 되어 있는데,
해당 부분에 대한 원리를 일러주신 것일까요? (그렇다면 감사합니다.)
아니라면 제가 놓친 부분이 있는지 궁금합니다.

2022-09-21 10:28 UTC, horsehair commented on src/news/news.repository.ts
> +        await this.delete(
반환값은 삭제한 뉴스의 정보입니다.(ReturnNewsDto)

2022-09-21 10:28 UTC, horsehair commented on src/news/news.repository.ts
> +        await this.delete(
에러 핸들링 로직은 필요할 것 같습니다.
이슈 생성 후 진행하겠습니다!

2022-09-21 10:34 UTC, horsehair commented on src/news/news.service.ts
> +    async updateAndGetAllNews(id: number, updateNewsDto: UpdateNewsDto) : Promise<News[] | void> {
1. 삭제 기능을 핸들링 한 후 --> 정확히 어떤 의미인지 이해하지 못했습니다.

2. 뉴스 전체를 가져오는 메소드를 추가로 호출한다. --> 현재 updateAndGetAllNews에서 updateNews(서비스 메소드) 호출 후 getAllNews(서비스 메소드)를 호출하는데,
updateNews에서 update기능을 수행한 후 바로 getAllNews를 호출하면 된다는 것을 의미하신 것일까요?

2022-09-21 10:34 UTC, horsehair commented on src/news/news.service.ts
> +        return await this.getAllNews();
위에 같은 이슈에 대해 질문 남겼습니다!

2022-09-21 10:34 UTC, horsehair commented on src/user/user.controller.spec.ts
> +    expect(controller).toBeDefined();
현재 구현된 부분까지 리팩토링하면서 같이 진행하겠습니다!

2022-09-21 10:41 UTC, horsehair commented on src/user/user.service.ts
> +    const userInfoForView = new UserInfoForView(
적용해서 아래에 푸쉬했습니다!

2022-09-21 10:42 UTC, horsehair commented on src/user/user.service.ts
> +    const userInfoForView = new UserInfoForView(
참고로 `DTO가` 아닌 `Dto`라고 사용한 것은 공식문서의 용례를 따랐습니다.
![image](https://user-images.githubusercontent.com/97939198/191484328-8bfeb715-731b-48f0-825a-b403fe01edb0.png)

2022-09-21 10:50 UTC, horsehair commented on src/user/user.module.ts
> +    PassportModule,
쿠키와 세션은 모두 세션 저장소를 사용하는데,
- 쿠키는 로컬, 세션은 로컬과 서버에 저장됩니다.
- 쿠키는 브라우저를 종료해도 파일을 남기지만, 세션은 브라우저 종료 시 삭제됩니다. -> 따라서 읽어들이는 속도는 쿠키가 상대적으로 빠릅니다. 세션은 요청마다 서버에서 처리 후 받아오기 때문에 느립니다.
- 쿠키 인증은 서버의 자원을 사용하지 않는 것이라, 클라이언트가 인증 정보를 책임집니다. -> 해커가 쿠키를 HTTP 요청 중간에서 뺏어갈 시 모든 정보가 탈취됩니다.  (보안과 관련 없는 기능에서 유용하게 사용됩니다.)

추가로 토큰은,
- 별도의 저장소가 필요하지 않습니다. (발급 후 검증만 하면 되기 때문에 / 때문에 stateless 합니다.) -> 서버가 유연해진다.

하지만 단점으로는,
- 토큰을 삭제하기 어렵습니다. (유효시간 내에 사용이 가능) -> Access Token과 Refresh Token을 분리하여 피해를 '줄일 수' 있습니다.

2022-09-21 10:50 UTC, horsehair commented
@sigridjineth 
리팩토링한 코드와, Comment로 남긴 질문 확인 부탁드립니다.

2022-09-23 13:27 UTC, sigridjineth commented on src/user/user.module.ts
> +    PassportModule,
토큰은 별도의 저장소가 필요하지 않다. -> 서버의 관점.
* JWT 토큰으로 자동 로그인을 구현한다.
* (세션 생각: 서버는 어떤 저장소 필요? 세션 아이디 : 사용자 아이디 DB - MySQL, MongoDB, Redis)
* (토큰 입장: 서버는 들고 있지 않다. -> 토큰 자체에 대한 유효성만 검증하면 되니까요.)
* Access Token, Refresh Token

OAuth2 vs JWT 뭔 차이일까요?
- 쿠키를 쓰면서 OAuth2
- OAuth2 X JWT O

2022-09-23 13:28 UTC, sigridjineth commented on src/user/user.module.ts
> +    PassportModule,
## 인증과 인가의 차이
* 인증은 로그인 -> OAuth2 인증
* 인가는 로그인이 이미 되어서, 쿠키든 토큰이든 이미 클라이언트에게 정보를 넘겨줬잖아요? 그러면 그 정보가 어디까지 접근 권한이 있는지를 확인하는 과정이죠. -> JWT AccessToken 인가

https://www.youtube.com/watch?v=JZgD8aPkHSc

2022-09-23 13:28 UTC, merged