Favorite response 형식을 수정한다.
DeliverBle/deliverble-backend-nestjs pull request #34
Opened 2022-09-24 18:01 UTC by horsehair

close #33 

### 수정 사항
- `toggleFavoriteNews`의 `response` 형식을 클라이언트 요청에 맞게 수정하였습니다.
- `add`, `delete`가 실행될 때 각각 `isFavorite`이 `true`, `false`로 반환됩니다.

2022-09-25 03:07 UTC, sigridjineth requested changes

2022-09-25 03:07 UTC, sigridjineth commented on src/user/user.controller.ts
> +      if (addOrDelete === "add") {
데이터를 가공하는 별도의 dedicated util이 있어보이면 좋을 것 같은데 어떠신가요?
그리고 ADD와 DELETE 액션만 있다면 type이나 enum 도입을 고려해보세요.

2022-09-25 03:07 UTC, sigridjineth commented on src/user/user.service.ts
> +    return "add";
type 활용에 대해 검토해보세요.
https://engineering.linecorp.com/ko/blog/typescript-enum-tree-shaking/

2022-09-26 04:11 UTC, horsehair commented on src/user/user.controller.ts
> +      if (addOrDelete === "add") {
넵 수정해보겠습니다~

2022-09-26 04:59 UTC, horsehair commented
요청주신 부분 수정해보았습니다.
- toggle여부 정보에 type 적용
- 새로운 모듈 생성 후 적용

2022-09-26 05:22 UTC, merged